### ISSUE TITLE
부하 테스트 해보기

### ISSUE THREAD

**Issue by eheh12321** [eheh12321/Look-At-Me_fork#28]
### JMeter를 이용한 부하 테스트 해보기 😸
- 서버 재부팅을 하고 나니까 생각보다 요청을 잘 처리함
- 어디까지 버티는지 테스트
- DB Connection 할 때 대기시간이 30000ms(30초)를 넘어가면 Timeout되기 때문에 에러 응답이 생길 것으로 추정

### Nginx 로그 확인
- `sudo tail -f /var/log/nginx/access.log`
- `sudo tail -f /var/log/nginx/error.log`

**Comment by eheh12321** [comment]
### Test 1.
**쓰레드 수: 500명
Ramp-up 시간: 30초
루프 카운트: 10회**

![스크린샷 2023-04-05 132634](https://user-images.githubusercontent.com/74748851/229980962-c2931b3f-d913-4f1a-afd9-0af99fef0136.png)

**최소 23ms
최대 6402ms
평균 2520ms
표준편차 1231ms
에러 0%**

![스크린샷 2023-04-05 132534](https://user-images.githubusercontent.com/74748851/229980961-d50bad20-3f1a-4848-b83d-62608a569584.png)
![스크린샷 2023-04-05 132642](https://user-images.githubusercontent.com/74748851/229980964-7f47683e-f25f-4196-94b3-f5477481377d.png)

**Comment by eheh12321** [comment]
## Test 2.
**쓰레드 수: 500명
Ramp-up 시간: 30초
루프 카운트: 20회**

![스크린샷 2023-04-05 135113](https://user-images.githubusercontent.com/74748851/229984422-40cbbdd6-286d-4418-b55e-80655fe6e38e.png)

**최대 7255ms
평균 3710ms
표준편차 1486ms
에러 2.01%**

![321](https://user-images.githubusercontent.com/74748851/229984430-b1ae1119-8c15-47a3-af9c-fab651731615.png)
![123](https://user-images.githubusercontent.com/74748851/229984434-450152ec-ef2f-4dae-bbab-948c440554d0.png)


## Test 3.
**쓰레드 수: 750명
Ramp-up 시간: 30초
루프 카운트: 20회**

![image](https://user-images.githubusercontent.com/74748851/229988856-90cde9e0-30a4-45a2-9b28-bbc412b9c666.png)

**최대 12625ms
평균 2118ms
표준편차 2462ms
에러 47.46%**

![image](https://user-images.githubusercontent.com/74748851/229988964-554eb970-47e6-42aa-a3fc-7595866c7610.png)
![image](https://user-images.githubusercontent.com/74748851/229988986-dacf1abc-d74e-41b1-b1aa-02964ce0758a.png)

**Comment by eheh12321** [comment]
## 발생하는 오류 목록
### 1. NoHttpResponseException
![스크린샷 2023-04-05 140707](https://user-images.githubusercontent.com/74748851/229986518-605ceef1-7966-43ba-8045-63fa59e0179d.png)

-> 서버로부터 응답을 받지 못한 경우. (서버에 부하가 걸려서 요청을 처리하지 못하는 경우)

### 2. SocketException
![스크린샷 2023-04-05 140733](https://user-images.githubusercontent.com/74748851/229986523-fcf51ad5-0b05-4ea0-bf36-4cd78ef9a414.png)

발생 원인
- 느린 네트워크 속도, 방화벽, 애플리케이션 에러 등...
- https://www.baeldung.com/java-socketexception

### 3. SSLHandshakeException
![스크린샷 2023-04-05 140713](https://user-images.githubusercontent.com/74748851/229986520-c7836c86-0aad-489b-8519-71b509c91f93.png)

## 추가
### 4. HttpHostConnectException
![image](https://user-images.githubusercontent.com/74748851/230248042-3f5c21b4-7d9e-46f7-ba22-0a535fba87eb.png)

-> 서버와의 연결에 실패한 경우

⭐ 해당 에러를 만드는 방법
- server.tomcat.* 설정으로 스레드 풀, 커넥션 설정을 만지면 Connection Refused 응답을 만들어낼 수 있음
- https://aljjabaegi.tistory.com/601
- spring.datasource.hikari.* 설정으로 DB의 커넥션 풀 설정을 만지면 500 에러를 만들 수 있음
- connection-timeout, maximum-pool-size를 줄이면 DB가 해당 요청을 모두 받지 못하고 에러를 던진다

**Comment by eheh12321** [comment]
DB 테스트를 하다가 ddl-auto가 create로 되어있는걸 생각 안하고 그냥 실행시켰다가 테이블이 전부 drop 되어버렸다.
백업 데이터가 없어서 복구가 안될 것 같다................................................. 👎
가망이 없다...........

**Comment by eheh12321** [comment]
### Embedded Tomcat 설정
```
server:
  tomcat:
    connection-timeout: 10 # 커넥션 타임아웃 시간 (초)
    max-connections: 10 # 주어진 시간 내에 처리할 수 있는 최대 커넥션 (최대 커넥션에 도달하면 이후 요청은 대기 큐에 추가)
    accept-count: 10 # 대기 큐의 길이 (대기 큐가 꽉 차면 스레드를 새로 추가)
    threads:
      max: 10 # Maximum amount of worker threads (스레드 허용치가 최대이고, 대기 큐까지 꽉 찬 상태라면 Connection Refused 에러를 던짐)
      min-spare: 10 # Minimum amount of worker threads (Core Size, 최초 생성 개수)
``` 

### DB Connection Pool 설정
```
spring:
  datasource:
    hikari:
      connection-timeout: 3000 # 쓰레드가 Connection을 얻기위해 대기하는 시간 (ms)
      maximum-pool-size: 2 # 스레드 풀의 최대 크기
      minimum-idle: 2 # 최초 스레드 생성 개수
      max-lifetime: 30000 # 커넥션 풀에서 사용되지 않는 idle 커넥션이 얼마동안 생존해 있을 것인지 (ms)
```

### ⭐ 참고 ⭐ 
- Tomcat의 Thread Pool과 DB의 Connection Pool은 서로 다름
- Thread Pool 크기와 Connection Pool 크기는 깊은 관련이 있음
- Pool 크기를 무한정 늘린다 해도 Context Switching 비용이 발생해 성능에 한계가 있음
